# Workflow for Angular CI build

name: Angular Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node 12.x
      uses: actions/setup-node@v1
    - name: npm install and npm run build
      run: |
        npm i
        npm run build:prod
    - name: FTP deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist/live-poll"
        remoteDir: "/root/live-poll/volumes/frontend"