# Workflow for Angular CI build

name: Angular Deploy

on:
  push:
    branches: [ develop ]
    paths-ignore: [ 'README.md', 'SECURITY.md', '.git**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install & Build
      run: |
        yarn install
        yarn run build:themes
        yarn run build:staging
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile -t ghcr.io/livepoll/live-poll-dev:latest
        echo "Build completed"

        echo ${CR_PAT} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"

        docker push ghcr.io/livepoll/live-poll-dev:latest
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
