# Workflow for Angular CI build

name: Angular Deploy

on:
  push:
    branches: [ develop ]
    paths-ignore: [ 'README.md', 'SECURITY.md', '.git**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Docker login GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install & Build
        run: |
          yarn install
          yarn run build:themes
          yarn run build:staging

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/livepoll/live-poll-dev:latest
          docker push ghcr.io/livepoll/live-poll-dev:latest

      - name: Prepare environment for localhost build
        run: |
          cp ./.github/files/environment.staging.ts ./src/environments/environment.staging.ts
          yarn run build:staging

      - name: Build Docker image for localhost
        run: |
          docker build . -t ghcr.io/livepoll/live-poll-dev:localhost
          docker push ghcr.io/livepoll/live-poll-dev:localhost