# Workflow for Angular CI build

name: Angular Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node 12.x
      uses: actions/setup-node@v1
    - name: npm install and npm run build
      run: |
        npm i
        npm run build:prod
    - name: Build Docker image
      run: | 
        docker build . --file Dockerfile -t docker.pkg.github.com/livepoll/live-poll/live-poll-dev:latest
        echo "Build completed"
        
        echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        
        docker push docker.pkg.github.com/livepoll/live-poll/live-poll-dev:latest    
        echo "Push successful"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}