# Workflow for Angular CI build

name: Angular Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node 12.x
      uses: actions/setup-node@v1
    - name: npm install and npm run build
      run: |
        npm i
        npm audit fix
        npm run build:prod
    - name: Build Docker image
      run: | 
        docker build . --file Dockerfile -t ghcr.io/livepoll/live-poll:latest
        echo "Build completed"
        
        echo ${CR_PAT} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        
        docker push ghcr.io/livepoll/live-poll:latest    
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}